on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest       
    name: Add steps to run
    steps:
     - uses: actions/checkout@v4.2.2
     - name: python set up 
       uses: actions/setup-python@v5
       with:
         python-version: '3.13'
     - name: Install dependencies
       run: |
         python -m pip install --upgrade pip
         pip install -r requirements.txt
     - name: Runt tests
       uses: actions/checkout@v4.2.2 
       if: success() || failure()
     - run: | 
          pwd
          cd Tests
          echo "Running tests"
          
     - name: Display Python version
       run: python3 -c "import sys; print(sys.version)"          
     
      
      
