on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest       
    name: Add steps to run
    steps:
     - uses: actions/checkout@v4.2.2
     - name: python set up 
       uses: actions/setup-python@v5
       with:
         python-version: '3.13'
     - name: Install dependencies
       run: |
         pip install --upgrade pip
         pip install -r requirements.txt
     - name: execute tests
       run: pytest --html=TestReport/testreport1.html -v -s
     - name: Display Python version
       run: python3 -c "import sys; print(sys.version)"          
     
      
      
